dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
script: mvn test -Dspring.profiles.active=mysql-travis

addons:
  sonarcloud:
    organization: "antromcac"
    token:
      secure: "lNK8rwzaT1LD/Jmwz152vYUrnJBxSIGALPeivsm87Z6CPQ5F4+Su91I1EOhM2MKjvDntHB/LU9vLlgHSPEa6k8pUtJoxC2fNGdU7J/nl8FOxXtuOGjKAGumNeM4RSrF/a9yR4Nk1HKdZBfcb1Ssxtfj+4XGODhIhLoPehzSBzhs+wHfXSE944kKOcV1RSTtJvcQNmsgrl87k7b9TR7ow8SELx03PcMz3t/AtaqfDUMIW06uptrPx2yfiQSQpbh3WUFAwUKBEiTp/+7mpJmndlY0NInD5p1NhBaGj5wAEEP7IviargprkHm8IkY38AHFmhQa9OUM44lNQb57r+4T0hqjYkRW7t7cttwThzoIeO/oFMrYbgNC6WDFvCTblkkz5YLAAxeZWklHvJZB+LPspCjl5Qpjh2SPHxRD/11Fmie2X09c0kTpQ6zxNyxQglaVfWCkIoEdBToJEOsL+JM2KqUbxM3JuVmFoBRMU8Fh1i2/W2BLSibQ6ihzRalY4P1tK/45XX8HChko89qlfIjLh/u8gszWMLA7SiXFyRwt0zeDrGgkR9kTqgxt/2rvl767T9XyAnXdX9YF/1YMY99ALWiyHZs5bbNCvYs29bt0QQn5GRBUEtURARVYcEbIe+KqsTxIKheYckakvZnWtj3AXhStnvV5pmGwoSIjja/5fc3Y="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
