dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
script: mvn test -Dspring.profiles.active=mysql-travis

addons:
    sonarcloud:
        organization: gii-is-psg2
        token:
            secure: rp0YmoiFl1Nrx9e/UhdZFKr8b/EaKQNCICBB810rMD8BFi3h6/xYf+qNwIr0Yd+5clsLpl8simLXDGU3OnZtaGSgCC81wiTkCEsOc3uD961qdz+PGHcbAoQxDO2xdbxZ2jRlFNbTT+M3+toOFiDE6eiJtr/7LbPgled7ccHUtTPd5mPNaUqx9Ok6wEdYbQjs8S8pAX/UHKwr5CTFfdIoYim4ver3M+kstdRPg30//k1aVbJHjua/51aeqJG1j2IY4GzNV/4jXU8fbnkj5f4zYZdXBOiiLSaUoJzxPL5gFgr/NcklLsJFUeKBCvxJmDP5E6cmb2yUTsQGln3vfXYcLypXNBcbmhDUXh4P5eLh3wj3rxTQS/EXzpf0zwLSgHtNmWBr4Ene2MOSF60pxuSNOWGKGPkmUqlnBPo02IpMGVbdH3w8/zrZBLintHayV04f6tTR7is+Zlqj6ZTN031QiQXXdejlVexlOUl3ZQAQI2C+4Y8YcqcDstT4CBuIP36T8BTorIwC1hd+yQN7N6AjRJF/mTErAeoxMELQl+hMEaa99k76JpQQECwApBWysAFwMjEzYJqmUR+Kx4sdjtHTUAHolx/b4XF2LUc1l6msYy2HsXDOiSORafuniCKyf9yFc3xXMc00Vgm40GGyVIGVvNfCg18fy5u9jQ19X0wbTUk=
script:
        # other script steps might be done before running the actual analysis
        - sonar-scanner
